companyName = ""
companyAddress = ""
companyZipCodeAndCity =""
companyPhone = ""
companyEmail = ""
companyWebsiteName = ""
companyWebsiteURL=""
companySiren = ""
companyTVAIntracom = ""
companyCapital = ""


clientName = ""
clientAdress = ""
clientZipCodeAndCity =""
clientPhoneNumber = ""